import { PrismaClient, Prisma } from '@prisma/client';
const prisma = new PrismaClient();

const initialPosts: Prisma.MemberCreateInput[] = [
  {
    membershipNo: 'M001',
    name: 'John Ali',
    dob: new Date('1980-01-01'),
    salutation: 'Mr',
    sex: 'M',
    dateJoined: new Date('2023-01-01'),
    collectionCentre: '1A',
    kraPin: 'A123456789B',
    address: '123 Main St, Nairobi',
    telephone: '+254700000000',
    email: 'john.doe@example.com',
    bank: 'Equity Bank',
    bankAc: '1234567890',
    division: 'Central',
    noOfCows: 5,
    cowsInMilk: 3,
    nationalIdNo: '12345678',
    nhifNo: 'NHIF001',
    nhifAmt: 500,
    village: 'Greenville',
    location: 'Nairobi',
    subLocation: 'Westlands',
    creditLimit: 10000,
    currentCreditUsed: 5000,
    membershipStatus: 'Active',
    statusDate: new Date('2023-01-01'),
    proposers: 'Jane Smith, Mike Johnson',
    comments: 'Reliable member',
    sharesPaid: 1000,
    nominee: {
      create: {
        nomineeName: 'Jane Doe',
        nomineeIdNo: '87654321',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '123 Main St, Nairobi',
        nomineeTelNo: '+254711111111',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R001', amount: 1000 },
        { receiptNo: 'R002', amount: 1500 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 100,
        entranceAlreadyPaid: 300,
        entranceExpected: 1000,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 500,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 200,
        newPlantAlreadyPaid: 600,
        newPlantExpected: 2000,
        newPlantCertificateNo: 'NPS001',
      },
    },
  },
  {
    membershipNo: 'M002',
    name: 'Alice Johnson',
    dob: new Date('1985-05-15'),
    salutation: 'Ms',
    sex: 'F',
    dateJoined: new Date('2023-02-01'),
    collectionCentre: '2A',
    kraPin: 'B987654321C',
    address: '456 Oak Ave, Mombasa',
    telephone: '+254722111111',
    email: 'alice.johnson@example.com',
    bank: 'KCB Bank',
    bankAc: '9876543210',
    division: 'Coast',
    noOfCows: 3,
    cowsInMilk: 2,
    nationalIdNo: '23456789',
    nhifNo: 'NHIF002',
    nhifAmt: 600,
    village: 'Seaside',
    location: 'Mombasa',
    subLocation: 'Nyali',
    creditLimit: 8000,
    currentCreditUsed: 3000,
    membershipStatus: 'Active',
    statusDate: new Date('2023-02-01'),
    proposers: 'Robert Brown, Sarah Lee',
    comments: 'New member with potential',
    sharesPaid: 800,
    nominee: {
      create: {
        nomineeName: 'Mark Johnson',
        nomineeIdNo: '76543210',
        nomineeRelationship: 'Brother',
        nomineeAddress: '456 Oak Ave, Mombasa',
        nomineeTelNo: '+254733222222',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R003', amount: 800 },
        { receiptNo: 'R004', amount: 1200 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 80,
        entranceAlreadyPaid: 240,
        entranceExpected: 800,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 400,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 150,
        newPlantAlreadyPaid: 450,
        newPlantExpected: 1500,
        newPlantCertificateNo: 'NPS002',
      },
    },
  },
  {
    membershipNo: 'M003',
    name: 'Robert Smith',
    dob: new Date('1975-09-22'),
    salutation: 'Mr',
    sex: 'M',
    dateJoined: new Date('2023-03-15'),
    collectionCentre: '3A',
    kraPin: 'C246813579D',
    address: '789 Pine Rd, Kisumu',
    telephone: '+254733333333',
    email: 'robert.smith@example.com',
    bank: 'Cooperative Bank',
    bankAc: '1357924680',
    division: 'Western',
    noOfCows: 7,
    cowsInMilk: 5,
    nationalIdNo: '34567890',
    nhifNo: 'NHIF003',
    nhifAmt: 700,
    village: 'Lakeside',
    location: 'Kisumu',
    subLocation: 'Milimani',
    creditLimit: 12000,
    currentCreditUsed: 6000,
    membershipStatus: 'Active',
    statusDate: new Date('2023-03-15'),
    proposers: 'David Wilson, Emma Davis',
    comments: 'Experienced farmer',
    sharesPaid: 1200,
    nominee: {
      create: {
        nomineeName: 'Mary Smith',
        nomineeIdNo: '65432109',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '789 Pine Rd, Kisumu',
        nomineeTelNo: '+254744444444',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R005', amount: 1200 },
        { receiptNo: 'R006', amount: 1800 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 120,
        entranceAlreadyPaid: 360,
        entranceExpected: 1200,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 600,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 250,
        newPlantAlreadyPaid: 750,
        newPlantExpected: 2500,
        newPlantCertificateNo: 'NPS003',
      },
    },
  },
  {
    membershipNo: 'M004',
    name: 'Emily Brown',
    dob: new Date('1988-12-10'),
    salutation: 'Mrs',
    sex: 'F',
    dateJoined: new Date('2023-04-01'),
    collectionCentre: '4A',
    kraPin: 'D135792468E',
    address: '101 Elm St, Nakuru',
    telephone: '+254755555555',
    email: 'emily.brown@example.com',
    bank: 'Family Bank',
    bankAc: '2468135790',
    division: 'Rift Valley',
    noOfCows: 4,
    cowsInMilk: 3,
    nationalIdNo: '45678901',
    nhifNo: 'NHIF004',
    nhifAmt: 550,
    village: 'Hillside',
    location: 'Nakuru',
    subLocation: 'London',
    creditLimit: 9000,
    currentCreditUsed: 4000,
    membershipStatus: 'Active',
    statusDate: new Date('2023-04-01'),
    proposers: 'Michael Green, Olivia Taylor',
    comments: 'Enthusiastic new member',
    sharesPaid: 900,
    nominee: {
      create: {
        nomineeName: 'James Brown',
        nomineeIdNo: '54321098',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '101 Elm St, Nakuru',
        nomineeTelNo: '+254766666666',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R007', amount: 900 },
        { receiptNo: 'R008', amount: 1350 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 90,
        entranceAlreadyPaid: 270,
        entranceExpected: 900,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 450,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 180,
        newPlantAlreadyPaid: 540,
        newPlantExpected: 1800,
        newPlantCertificateNo: 'NPS004',
      },
    },
  },
  {
    membershipNo: 'M005',
    name: 'David Wilson',
    dob: new Date('1970-07-07'),
    salutation: 'Mr',
    sex: 'M',
    dateJoined: new Date('2023-05-01'),
    collectionCentre: '5A',
    kraPin: 'E864209753F',
    address: '202 Maple Ave, Eldoret',
    telephone: '+254777777777',
    email: 'david.wilson@example.com',
    bank: 'Absa Bank',
    bankAc: '3579246801',
    division: 'North Rift',
    noOfCows: 10,
    cowsInMilk: 7,
    nationalIdNo: '56789012',
    nhifNo: 'NHIF005',
    nhifAmt: 800,
    village: 'Farmville',
    location: 'Eldoret',
    subLocation: 'Pioneer',
    creditLimit: 15000,
    currentCreditUsed: 7500,
    membershipStatus: 'Active',
    statusDate: new Date('2023-05-01'),
    proposers: 'William Clark, Sophia Martinez',
    comments: 'Large-scale farmer',
    sharesPaid: 1500,
    nominee: {
      create: {
        nomineeName: 'Elizabeth Wilson',
        nomineeIdNo: '43210987',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '202 Maple Ave, Eldoret',
        nomineeTelNo: '+254788888888',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R009', amount: 1500 },
        { receiptNo: 'R010', amount: 2250 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 150,
        entranceAlreadyPaid: 450,
        entranceExpected: 1500,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 750,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 300,
        newPlantAlreadyPaid: 900,
        newPlantExpected: 3000,
        newPlantCertificateNo: 'NPS005',
      },
    },
  },
  {
    membershipNo: 'M006',
    name: 'Sarah Lee',
    dob: new Date('1982-03-25'),
    salutation: 'Ms',
    sex: 'F',
    dateJoined: new Date('2023-06-01'),
    collectionCentre: '6A',
    kraPin: 'F975310864G',
    address: '303 Cedar Ln, Thika',
    telephone: '+254799999999',
    email: 'sarah.lee@example.com',
    bank: 'Standard Chartered',
    bankAc: '4680135792',
    division: 'Central',
    noOfCows: 6,
    cowsInMilk: 4,
    nationalIdNo: '67890123',
    nhifNo: 'NHIF006',
    nhifAmt: 650,
    village: 'Riverside',
    location: 'Thika',
    subLocation: 'Makongeni',
    creditLimit: 11000,
    currentCreditUsed: 5500,
    membershipStatus: 'Active',
    statusDate: new Date('2023-06-01'),
    proposers: 'Daniel Brown, Olivia Johnson',
    comments: 'Dedicated member',
    sharesPaid: 1100,
    nominee: {
      create: {
        nomineeName: 'Thomas Lee',
        nomineeIdNo: '32109876',
        nomineeRelationship: 'Brother',
        nomineeAddress: '303 Cedar Ln, Thika',
        nomineeTelNo: '+254710101010',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R011', amount: 1100 },
        { receiptNo: 'R012', amount: 1650 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 110,
        entranceAlreadyPaid: 330,
        entranceExpected: 1100,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 550,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 220,
        newPlantAlreadyPaid: 660,
        newPlantExpected: 2200,

        newPlantCertificateNo: 'NPS006',
      },
    },
  },
  {
    membershipNo: 'M007',
    name: 'Michael Green',
    dob: new Date('1978-11-30'),
    salutation: 'Mr',
    sex: 'M',
    dateJoined: new Date('2023-07-01'),
    collectionCentre: '1A',
    kraPin: 'G753108642H',
    address: '404 Birch Rd, Machakos',
    telephone: '+254712121212',
    email: 'michael.green@example.com',
    bank: 'Stanbic Bank',
    bankAc: '5791324680',
    division: 'Eastern',
    noOfCows: 8,
    cowsInMilk: 6,
    nationalIdNo: '78901234',
    nhifNo: 'NHIF007',
    nhifAmt: 750,
    village: 'Hilltop',
    location: 'Machakos',
    subLocation: 'Mlolongo',
    creditLimit: 13000,
    currentCreditUsed: 6500,
    membershipStatus: 'Active',
    statusDate: new Date('2023-07-01'),
    proposers: 'Christopher Lee, Emma Wilson',
    comments: 'Innovative farmer',
    sharesPaid: 1300,
    nominee: {
      create: {
        nomineeName: 'Rachel Green',
        nomineeIdNo: '21098765',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '404 Birch Rd, Machakos',
        nomineeTelNo: '+254723232323',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R013', amount: 1300 },
        { receiptNo: 'R014', amount: 1950 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 130,
        entranceAlreadyPaid: 390,
        entranceExpected: 1300,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 650,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 260,
        newPlantAlreadyPaid: 780,
        newPlantExpected: 2600,
        newPlantCertificateNo: 'NPS007',
      },
    },
  },
  {
    membershipNo: 'M008',
    name: 'Olivia Taylor',
    dob: new Date('1990-08-18'),
    salutation: 'Ms',
    sex: 'F',
    dateJoined: new Date('2023-08-01'),
    collectionCentre: '2A',
    kraPin: 'H531086429I',
    address: '505 Walnut St, Nyeri',
    telephone: '+254734343434',
    email: 'olivia.taylor@example.com',
    bank: 'DTB Bank',
    bankAc: '6802468135',
    division: 'Central',
    noOfCows: 5,
    cowsInMilk: 3,
    nationalIdNo: '89012345',
    nhifNo: 'NHIF008',
    nhifAmt: 600,
    village: 'Mountainview',
    location: 'Nyeri',
    subLocation: 'Ruring',
    creditLimit: 10000,
    currentCreditUsed: 5000,
    membershipStatus: 'Active',
    statusDate: new Date('2023-08-01'),
    proposers: 'Andrew Davis, Isabella Martinez',
    comments: 'Young and ambitious farmer',
    sharesPaid: 1000,
    nominee: {
      create: {
        nomineeName: 'Ethan Taylor',
        nomineeIdNo: '10987654',
        nomineeRelationship: 'Brother',
        nomineeAddress: '505 Walnut St, Nyeri',
        nomineeTelNo: '+254745454545',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R015', amount: 1000 },
        { receiptNo: 'R016', amount: 1500 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 100,
        entranceAlreadyPaid: 300,
        entranceExpected: 1000,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 500,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 200,
        newPlantAlreadyPaid: 600,
        newPlantExpected: 2000,
        newPlantCertificateNo: 'NPS008',
      },
    },
  },
  {
    membershipNo: 'M009',
    name: 'William Clark',
    dob: new Date('1972-06-05'),
    salutation: 'Mr',
    sex: 'M',
    dateJoined: new Date('2023-09-01'),
    collectionCentre: '3A',
    kraPin: 'I309875421J',
    address: '606 Oak Ave, Kakamega',
    telephone: '+254756565656',
    email: 'william.clark@example.com',
    bank: 'I&M Bank',
    bankAc: '7913579246',
    division: 'Western',
    noOfCows: 9,
    cowsInMilk: 7,
    nationalIdNo: '90123456',
    nhifNo: 'NHIF009',
    nhifAmt: 800,
    village: 'Forestview',
    location: 'Kakamega',
    subLocation: 'Lurambi',
    creditLimit: 14000,
    currentCreditUsed: 7000,
    membershipStatus: 'Active',
    statusDate: new Date('2023-09-01'),
    proposers: 'Robert Johnson, Sophia Brown',
    comments: 'Experienced dairy farmer',
    sharesPaid: 1400,
    nominee: {
      create: {
        nomineeName: 'Catherine Clark',
        nomineeIdNo: '09876543',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '606 Oak Ave, Kakamega',
        nomineeTelNo: '+254767676767',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R017', amount: 1400 },
        { receiptNo: 'R018', amount: 2100 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 140,
        entranceAlreadyPaid: 420,
        entranceExpected: 1400,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 700,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 280,
        newPlantAlreadyPaid: 840,
        newPlantExpected: 2800,
        newPlantCertificateNo: 'NPS009',
      },
    },
  },
  {
    membershipNo: 'M010',
    name: 'Sophia Martinez',
    dob: new Date('1987-02-14'),
    salutation: 'Mrs',
    sex: 'F',
    dateJoined: new Date('2023-10-01'),
    collectionCentre: '4A',
    kraPin: 'J086429753K',
    address: '707 Pine Ln, Kitale',
    telephone: '+254778787878',
    email: 'sophia.martinez@example.com',
    bank: 'NCBA Bank',
    bankAc: '8024681357',
    division: 'North Rift',
    noOfCows: 7,
    cowsInMilk: 5,
    nationalIdNo: '01234567',
    nhifNo: 'NHIF010',
    nhifAmt: 700,
    village: 'Valleyview',
    location: 'Kitale',
    subLocation: 'Kibomet',
    creditLimit: 12000,
    currentCreditUsed: 6000,
    membershipStatus: 'Active',
    statusDate: new Date('2023-10-01'),
    proposers: 'Daniel Wilson, Emily Taylor',
    comments: 'Committed member',
    sharesPaid: 1200,
    nominee: {
      create: {
        nomineeName: 'Carlos Martinez',
        nomineeIdNo: '98765432',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '707 Pine Ln, Kitale',
        nomineeTelNo: '+254789898989',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R019', amount: 1200 },
        { receiptNo: 'R020', amount: 1800 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 120,
        entranceAlreadyPaid: 360,
        entranceExpected: 1200,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 600,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 240,
        newPlantAlreadyPaid: 720,
        newPlantExpected: 2400,
        newPlantCertificateNo: 'NPS010',
      },
    },
  },
  {
    membershipNo: 'M011',
    name: 'Daniel Brown',
    dob: new Date('1983-09-08'),
    salutation: 'Mr',
    sex: 'M',
    dateJoined: new Date('2023-11-01'),
    collectionCentre: '5A',
    kraPin: 'K864209753L',
    address: '808 Elm Rd, Kisii',
    telephone: '+254790909090',
    email: 'daniel.brown@example.com',
    bank: 'Sidian Bank',
    bankAc: '9135792468',
    division: 'Nyanza',
    noOfCows: 6,
    cowsInMilk: 4,
    nationalIdNo: '12345678',
    nhifNo: 'NHIF011',
    nhifAmt: 650,
    village: 'Hillcrest',
    location: 'Kisii',
    subLocation: 'Nyamataro',
    creditLimit: 11000,
    currentCreditUsed: 5500,
    membershipStatus: 'Active',
    statusDate: new Date('2023-11-01'),
    proposers: 'Michael Green, Sarah Lee',
    comments: 'Promising new member',
    sharesPaid: 1100,
    nominee: {
      create: {
        nomineeName: 'Olivia Brown',
        nomineeIdNo: '87654321',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '808 Elm Rd, Kisii',
        nomineeTelNo: '+254701010101',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R021', amount: 1100 },
        { receiptNo: 'R022', amount: 1650 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 110,
        entranceAlreadyPaid: 330,
        entranceExpected: 1100,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 550,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 220,
        newPlantAlreadyPaid: 660,
        newPlantExpected: 2200,
        newPlantCertificateNo: 'NPS011',
      },
    },
  },
  {
    membershipNo: 'M012',
    name: 'Emma Davis',
    dob: new Date('1976-12-20'),
    salutation: 'Ms',
    sex: 'F',
    dateJoined: new Date('2023-12-01'),
    collectionCentre: '6A',
    kraPin: 'L642097531M',
    address: '909 Maple St, Embu',
    telephone: '+254712121212',
    email: 'emma.davis@example.com',
    bank: 'Gulf African Bank',
    bankAc: '0246813579',
    division: 'Eastern',
    noOfCows: 8,
    cowsInMilk: 6,
    nationalIdNo: '23456789',
    nhifNo: 'NHIF012',
    nhifAmt: 750,
    village: 'Riverside',
    location: 'Embu',
    subLocation: 'Dallas',
    creditLimit: 13000,
    currentCreditUsed: 6500,
    membershipStatus: 'Active',
    statusDate: new Date('2023-12-01'),
    proposers: 'William Clark, Olivia Taylor',
    comments: 'Experienced in dairy farming',
    sharesPaid: 1300,
    nominee: {
      create: {
        nomineeName: 'George Davis',
        nomineeIdNo: '76543210',
        nomineeRelationship: 'Brother',
        nomineeAddress: '909 Maple St, Embu',
        nomineeTelNo: '+254723232323',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R023', amount: 1300 },
        { receiptNo: 'R024', amount: 1950 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 130,
        entranceAlreadyPaid: 390,
        entranceExpected: 1300,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 650,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 260,
        newPlantAlreadyPaid: 780,
        newPlantExpected: 2600,
        newPlantCertificateNo: 'NPS012',
      },
    },
  },
  {
    membershipNo: 'M013',
    name: 'Christopher Lee',
    dob: new Date('1981-04-03'),
    salutation: 'Mr',
    sex: 'M',
    dateJoined: new Date('2024-01-01'),
    collectionCentre: '1A',
    kraPin: '420975310N',
    address: '1010 Cedar Ave, Nyahururu',
    telephone: '+254734343434',
    email: 'christopher.lee@example.com',
    bank: 'Prime Bank',
    bankAc: '1357924680',
    division: 'Central',
    noOfCows: 5,
    cowsInMilk: 3,
    nationalIdNo: '34567890',
    nhifNo: 'NHIF013',
    nhifAmt: 600,
    village: 'Lakeside',
    location: 'Nyahururu',
    subLocation: 'Manguo',
    creditLimit: 10000,
    currentCreditUsed: 5000,
    membershipStatus: 'Active',
    statusDate: new Date('2024-01-01'),
    proposers: 'Robert Smith, Alice Johnson',
    comments: 'Enthusiastic about dairy farming',
    sharesPaid: 1000,
    nominee: {
      create: {
        nomineeName: 'Jennifer Lee',
        nomineeIdNo: '65432109',
        nomineeRelationship: 'Spouse',
        nomineeAddress: '1010 Cedar Ave, Nyahururu',
        nomineeTelNo: '+254745454545',
      },
    },
    payments: {
      create: [
        { receiptNo: 'R025', amount: 1000 },
        { receiptNo: 'R026', amount: 1500 },
      ],
    },
    entranceFee: {
      create: {
        entranceMonthlyDeduction: 100,
        entranceAlreadyPaid: 300,
        entranceExpected: 1000,
      },
    },
    monthlyContribution: {
      create: {
        monthlyNormal: 500,
        monthlyOverride: 0,
        monthlyOverrideBal: 0,
      },
    },
    newPlantShares: {
      create: {
        newPlantMonthlyDeduction: 200,
        newPlantAlreadyPaid: 600,
        newPlantExpected: 2000,
        newPlantCertificateNo: 'NPS013',
      },
    },
  },
];

async function main() {
  console.log('Start seeding...');

  for (const post of initialPosts) {
    const newPost = await prisma.member.create({
      data: post,
    });

    console.log(`Created post with id ${newPost.id}`);
  }

  console.log('Seeding finished.');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
